all:
  children:
    masters:
      hosts:
        localhost:
          ansible_connection: local
    computes:
      hosts:
        localhost:
          ansible_connection: local


#    switches:
#      hosts:
#    rans:
#      hosts:
#        10.64.45.22:
#          xx-name: bp2
